<?php

/**
 * @file
 * This is the module to create synchronization with windows azure storage.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param string $route_name
 *   The route name of the page.
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *   The route match.
 *
 * @return string
 */
function windows_azure_storage_help(string $route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.windows_azure_storage':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Windows Azure Storage module allows for files to be uploaded to the Windows Azure storage service.') . '</p>';
      $output .= '<h3>' . t('Instructions') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Adding a custom blob stream') . '</dt>';
      $output .= '<dd>' . t('Configuration > Media > Windows Azure Storage > Add new confiruration') . '</dd>';
      $output .= '<dt>' . t('Setting the upload destination of content type fields') . '</dt>';
      $output .= '<dd>' . t('Configuration > Text formarts and editors > Full Html > Configure > CKEditor plugin settings > File storage > Choose Windows Azure Storage') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}
